export type SearchItem = {
  title: string;
  category: string;
  href: string;
  desc: string;
};

export const SEARCH_INDEX: SearchItem[] = [
  {
    title: "Văn phòng ảo",
    category: "Dịch vụ",
    href: "/services/van-phong-ao",
    desc: "Từ 299.000đ/tháng — địa chỉ đăng ký kinh doanh hợp lệ",
  },
  {
    title: "Văn phòng trọn gói",
    category: "Dịch vụ",
    href: "/services/van-phong-tron-goi",
    desc: "Từ 4.500.000đ/tháng — không gian riêng, sẵn sàng làm việc ngay",
  },
  {
    title: "Chỗ ngồi linh động",
    category: "Dịch vụ",
    href: "/services/cho-ngoi-linh-dong",
    desc: "Từ 2.000.000đ/tháng — coworking cho freelancer & nhóm nhỏ",
  },
  {
    title: "Phòng họp theo giờ",
    category: "Dịch vụ",
    href: "/services/phong-hop",
    desc: "Từ 150.000đ/giờ — trang bị màn hình, âm thanh hiện đại",
  },
  {
    title: "Thành lập doanh nghiệp",
    category: "Dịch vụ",
    href: "/services/thanh-lap-doanh-nghiep",
    desc: "Từ 1.299.000đ* — Gói 1 & Gói 2, áp dụng chung mọi loại hình",
  },
  {
    title: "Kế toán & thuế",
    category: "Dịch vụ",
    href: "/services/ke-toan-thue",
    desc: "Từ 500.000đ/tháng — kê khai thuế, sổ sách minh bạch",
  },
  {
    title: "Dịch vụ pháp lý sửa đổi doanh nghiệp",
    category: "Dịch vụ",
    href: "/dich-vu/dich-vu-phap-ly-sua-doi",
    desc: "Đổi tên, địa chỉ, đại diện pháp luật, vốn điều lệ... ưu đãi combo từ 2 dịch vụ",
  },
  {
    title: "Điện Biên Phủ, Quận 1",
    category: "Chi nhánh",
    href: "/locations/dien-bien-phu",
    desc: "Số 95 Điện Biên Phủ, P. Tân Định — Vị trí VIP",
  },
  {
    title: "Sông Thao, Tân Bình",
    category: "Chi nhánh",
    href: "/locations/song-thao",
    desc: "Số 10 Sông Thao, P. Tân Sơn Hoà — Trụ sở chính",
  },
  {
    title: "Nguyễn Oanh, Gò Vấp",
    category: "Chi nhánh",
    href: "/locations/nguyen-oanh",
    desc: "238-240-242 Nguyễn Oanh, P. Gò Vấp",
  },
  {
    title: "Yên Thế, Tân Bình",
    category: "Chi nhánh",
    href: "/locations/yen-the",
    desc: "92 Yên Thế, P. Tân Sơn Hòa",
  },
  {
    title: "Cộng Hoà, Tân Bình",
    category: "Chi nhánh",
    href: "/locations/cong-hoa",
    desc: "123 Cộng Hoà, P. Bảy Hiền",
  },
  {
    title: "Tân Thắng, Tân Phú",
    category: "Chi nhánh",
    href: "/locations/tan-thang",
    desc: "121A-123-125 Tân Thắng, P. Tân Sơn Nhì",
  },
  {
    title: "Cửu Long, Tân Bình",
    category: "Chi nhánh",
    href: "/locations/cuu-long",
    desc: "06-08-10 Cửu Long, P. Tân Sơn Hòa",
  },
  {
    title: "Hoàng Việt, Tân Bình",
    category: "Chi nhánh",
    href: "/locations/hoang-viet",
    desc: "1/12 Hoàng Việt, P. Tân Sơn Nhất",
  },
  {
    title: "Bàu Cát 2, Tân Bình",
    category: "Chi nhánh",
    href: "/locations/bau-cat",
    desc: "24A Bàu Cát 2, P. Tân Bình",
  },
  {
    title: "Lam Sơn, Tân Bình",
    category: "Chi nhánh",
    href: "/locations/lam-son",
    desc: "2-2B Lam Sơn, P. Tân Sơn Hòa",
  },
  {
    title: "Hoàng Kế Viêm, Tân Bình",
    category: "Chi nhánh",
    href: "/locations/hoang-ke-viem",
    desc: "26 Hoàng Kế Viêm, P. Bảy Hiền",
  },
  {
    title: "CMT8, Quận 10",
    category: "Chi nhánh",
    href: "/locations/cmt8",
    desc: "283/26-28 CMT8, P. Hoà Hưng",
  },
  {
    title: "Bảng giá Văn phòng & Coworking",
    category: "Bảng giá",
    href: "/bang-gia",
    desc: "Văn phòng ảo, trọn gói, coworking, phòng họp",
  },
  {
    title: "Bảng giá Thành lập doanh nghiệp",
    category: "Bảng giá",
    href: "/bang-gia",
    desc: "Gói 1 & Gói 2, áp dụng chung mọi loại hình doanh nghiệp",
  },
  {
    title: "Bảng giá Kế toán & Thuế",
    category: "Bảng giá",
    href: "/bang-gia",
    desc: "Từ 500.000đ/tháng, theo số hoá đơn/quý và loại hình kinh doanh",
  },
  {
    title: "Nên chọn Hộ kinh doanh hay Công ty TNHH?",
    category: "Kiến thức",
    href: "/knowledge-center/thanh-lap-doanh-nghiep",
    desc: "So sánh ưu, nhược điểm từng loại hình doanh nghiệp",
  },
  {
    title: "5 điều cần biết trước khi thuê văn phòng ảo",
    category: "Kiến thức",
    href: "/knowledge-center/van-phong-dia-diem",
    desc: "Kinh nghiệm chọn đúng địa chỉ đăng ký kinh doanh",
  },
  {
    title: "Lịch nộp thuế doanh nghiệp cần nhớ",
    category: "Kiến thức",
    href: "/knowledge-center/ke-toan-thue",
    desc: "Tổng hợp các mốc kê khai, nộp thuế quan trọng",
  },
  {
    title: "Thủ tục mở chi nhánh tại TP.HCM",
    category: "Kiến thức",
    href: "/knowledge-center/mo-rong-kinh-doanh",
    desc: "Hướng dẫn hồ sơ, quy trình đăng ký chi nhánh",
  },
  {
    title: "Giấy Phép Kinh Doanh",
    category: "Kiến thức",
    href: "/knowledge-center/giay-phep-kinh-doanh",
    desc: "Điều kiện, thủ tục xin giấy phép con cho ngành nghề có điều kiện",
  },
  {
    title: "Pháp Lý Doanh Nghiệp",
    category: "Kiến thức",
    href: "/knowledge-center/phap-ly-doanh-nghiep",
    desc: "Quy định pháp luật, hợp đồng và rủi ro pháp lý cần biết",
  },
  {
    title: "Startup & Khởi Nghiệp",
    category: "Kiến thức",
    href: "/knowledge-center/startup-khoi-nghiep",
    desc: "Kinh nghiệm khởi nghiệp, gọi vốn và xây dựng đội ngũ",
  },
  {
    title: "Quản Lý Tài Chính",
    category: "Kiến thức",
    href: "/knowledge-center/quan-ly-tai-chinh",
    desc: "Dòng tiền, ngân sách và kiểm soát tài chính doanh nghiệp",
  },
  {
    title: "Kiến thức doanh nghiệp — Cẩm nang MAX OFFICE",
    category: "Trang",
    href: "/knowledge-center",
    desc: "8 chuyên mục kiến thức pháp lý, thuế và vận hành doanh nghiệp",
  },
  {
    title: "Blog MAX OFFICE",
    category: "Trang",
    href: "/blog",
    desc: "Bài viết về thành lập doanh nghiệp, kế toán thuế và vận hành văn phòng",
  },
  {
    title: "Văn phòng ảo có được dùng để đăng ký kinh doanh không?",
    category: "Câu hỏi thường gặp",
    href: "/#faq",
    desc: "Có, địa chỉ văn phòng ảo hoàn toàn hợp lệ",
  },
  {
    title: "Thời gian hoàn tất thủ tục thành lập công ty",
    category: "Câu hỏi thường gặp",
    href: "/#faq",
    desc: "Thông thường từ 3-5 ngày làm việc",
  },
  {
    title: "Về chúng tôi",
    category: "Trang",
    href: "/ve-chung-toi",
    desc: "Câu chuyện, tầm nhìn, sứ mệnh và hành trình phát triển của MAX OFFICE",
  },
  {
    title: "Bảng giá dịch vụ",
    category: "Trang",
    href: "/bang-gia",
    desc: "Bảng so sánh chi tiết tất cả gói dịch vụ, minh bạch không phát sinh",
  },
  {
    title: "Liên hệ MAX OFFICE",
    category: "Trang",
    href: "/lien-he",
    desc: "Nhận tư vấn miễn phí — gọi ngay 089 8082 188",
  },
  {
    title: "Tiện ích miễn phí",
    category: "Trang",
    href: "/tien-ich",
    desc: "3 công cụ miễn phí hỗ trợ doanh nghiệp",
  },
  {
    title: "Công cụ chọn gói văn phòng phù hợp",
    category: "Tiện ích",
    href: "/tien-ich/chon-goi-van-phong",
    desc: "Trả lời 5 câu hỏi để nhận gợi ý gói văn phòng phù hợp",
  },
  {
    title: "Công cụ tính chi phí thành lập công ty",
    category: "Tiện ích",
    href: "/tien-ich/tinh-chi-phi-thanh-lap",
    desc: "Ước tính chi phí thành lập theo bảng giá mới nhất",
  },
  {
    title: "Lệ phí môn bài đã bãi bỏ",
    category: "Tiện ích",
    href: "/tien-ich/tinh-le-phi-mon-bai",
    desc: "Cập nhật quy định mới: bãi bỏ từ 01/01/2026 theo Nghị quyết 198/2025/QH15",
  },
  {
    title: "Checklist thành lập doanh nghiệp",
    category: "Tiện ích",
    href: "/tien-ich/checklist-thanh-lap-doanh-nghiep",
    desc: "Các bước và giấy tờ cần chuẩn bị khi thành lập doanh nghiệp, tải PDF miễn phí",
  },
  {
    title: "Checklist mở chi nhánh",
    category: "Tiện ích",
    href: "/tien-ich/checklist-mo-chi-nhanh",
    desc: "Các bước và giấy tờ khi mở chi nhánh công ty, tải PDF miễn phí",
  },
  {
    title: "Checklist thay đổi giấy phép kinh doanh",
    category: "Tiện ích",
    href: "/tien-ich/checklist-thay-doi-giay-phep-kinh-doanh",
    desc: "Các bước khi đổi tên, địa chỉ, ngành nghề hoặc vốn điều lệ",
  },
  {
    title: "So sánh Văn phòng ảo & Văn phòng trọn gói",
    category: "Tiện ích",
    href: "/tien-ich/so-sanh-van-phong-ao-va-tron-goi",
    desc: "Bảng so sánh tính năng, chi phí và đối tượng phù hợp",
  },
  {
    title: "So sánh Công ty TNHH & Công ty Cổ phần",
    category: "Tiện ích",
    href: "/tien-ich/so-sanh-tnhh-va-co-phan",
    desc: "Vốn điều lệ, cơ cấu quản lý và chi phí thành lập",
  },
  {
    title: "Quy trình thành lập doanh nghiệp",
    category: "Tiện ích",
    href: "/tien-ich/quy-trinh-thanh-lap-doanh-nghiep",
    desc: "Timeline tương tác toàn bộ hành trình thành lập doanh nghiệp",
  },
];
